dataset: ogbg-mollipo
num_workers: 12
model:
  arch_type: KCSetGNN
  bgnn_type: Sequential
  gnn_type: GINEConv
  half_step: False 
  hidden_size: 64
  num_layers: 4
  num_inners: 4
  pools: [add]
subgraph:
  type: kWL
  stack: True
  num_components: 1
  kmax: 4
  zero_init: False
train:
  lr_patience: 50
  dropout: 0.
  epochs: 120
  runs: 2
  batch_size: 40